apiVersion: v1
kind: List
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: db-pvc
  spec:
    accessModes:
    # can be used by single node only
    - ReadWriteOnce
    ## can be read by many nodes:
    #- ReadOnlyMany
    ## can be read and writed by many nodes
    #- ReadWriteMany
    resources:
      requests:
        storage: 1Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: db-deployment
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: postgres
    template:
      metadata:
        labels:
          run: postgres
      spec:
        volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: db-pvc
        containers:
        - name: postgres
          image: healthcheck/postgres
          ports:
          - containerPort: 5432
          volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
            subPath: postgres
- apiVersion: v1
  kind: Service
  metadata:
    name: db-clister-ip-service
  spec:
    selector:
      run: postgres
    ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
