apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      run: web
    name: web
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: web
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          run: web
      spec:
        containers:
        - image: nginx:1.15.5-alpine
          imagePullPolicy: IfNotPresent
          name: web
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: web
    name: web
  spec:
    ports:
    - nodePort: 30000
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      run: web
    type: NodePort

