apiVersion: v1
kind: Service
metadata:
  labels:
    run: web
  name: web
  namespace: default
  selfLink: /api/v1/namespaces/default/services/web
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost
